sut:
  build: .
  command: test
  entrypoint: npm
  environment:
    - CI
  links:
    - bitcoind
    - bitcoind-ssl
    - bitcoind-username-only

bitcoind:
  image: seegno/bitcoind:0.12-alpine
  command:
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcpassword=bar
    -rpcuser=foo
    -server

bitcoind-ssl:
  image: seegno/bitcoind:0.11-alpine
  command:
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcpassword=bar
    -rpcssl
    -rpcsslcertificatechainfile=/etc/ssl/bitcoind/cert.pem
    -rpcsslprivatekeyfile=/etc/ssl/bitcoind/key.pem
    -rpcuser=foo
    -server
  volumes:
    - ./test/config/ssl:/etc/ssl/bitcoind

bitcoind-username-only:
  image: seegno/bitcoind:0.11-alpine
  command:
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcallowip=192.168.0.0/16
    -rpcuser=foo
    -server
