sut:
  build: .
  command: test
  entrypoint: npm
  links:
    - bitcoind
    - bitcoind-ssl
    - bitcoind-username-only

bitcoind:
  image: seegno/bitcoind:0.12
  command:
    -datadir=/var/lib/bitcoind
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcpassword=bar
    -rpcuser=foo
    -server
  ports:
    - 18332

bitcoind-ssl:
  image: seegno/bitcoind:0.11
  command:
    -datadir=/var/lib/bitcoind
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcpassword=bar
    -rpcssl
    -rpcsslcertificatechainfile=/etc/ssl/bitcoind/cert.pem
    -rpcsslprivatekeyfile=/etc/ssl/bitcoind/key.pem
    -rpcuser=foo
    -server
  ports:
    - 18332
  volumes:
    - ./test/config/ssl:/etc/ssl/bitcoind

bitcoind-username-only:
  image: seegno/bitcoind:0.11
  command:
    -datadir=/var/lib/bitcoind
    -printtoconsole
    -regtest=1
    -rest
    -rpcallowip=10.211.0.0/16
    -rpcallowip=172.17.0.0/16
    -rpcuser=foo
    -server
  ports:
    - 18332
